# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb', 'deploy.sh']
markdown: rdiscount

# configuration required for some pages

domain: www.veterinariahomeopatia.com.br
title: Homeopatia Veterinária
author: Maria Eugenia Carretero
email: maru.veterinaria@gmail.com

